TUNE("Alla Turca", alla_turca)
TUNE("Atomix", atomix)
TUNE("Axel F. The"/*me"*/, axel_f_theme)
TUNE("Aztec", aztec)
TUNE("B2 Silver", b2_silver)
TUNE("Belegost", belegost)
TUNE("Cantina", cantina)
TUNE("Chimera", chimera)
TUNE("Commando", commando)
TUNE("Crazy Comet"/*s and Penetrator"*/, crazy_comets_and_penetrator)
//TUNE("Dizzy", dizzy)
//TUNE("Dizzy4", dizzy4)
//TUNE("Dizzy6", dizzy6)
//TUNE("DizzySACK", dizzy_sack)
TUNE("E.T. Flying", e_t_flying)
TUNE("Eqinoxe V", eqinoxe_v)
TUNE("ExplodingAt"/*oms"*/, exploding_atoms)
TUNE("Falcon", falcon)
TUNE("Feud", feud)
TUNE("FIRE", fire)
TUNE("Fugue", fugue)
TUNE("Ghostbuster"/*s"*/, ghostbusters)
TUNE("Golden Tria"/*ngle Anthem"*/, golden_triangle_anthem)
TUNE("Indiana Jon"/*es 3"*/, indiana_jones_3)
TUNE("Jet Story", jet_story)
TUNE("Kino/Sun", kino_sun)
TUNE("Kukushka", kukushka)
TUNE("Land Of Con"/*fusion"*/, land_of_confusion)
TUNE("Magnetic Fi"/*elds IV"*/, magnetic_fields_iv)
TUNE("Magnetic Fi"/*elds V"*/, magnetic_fields_v)
TUNE("Mario", mario)
TUNE("Master of M"/*agic"*/, master_of_magic)
TUNE("Monty On Th"/*e Run"*/, monty_on_the_run)
TUNE("Piskworks-T"/*opgun"*/, piskworks_topgun)
TUNE("Red dawn", red_dawn)
TUNE("RendezVous "/*IV"*/, rendezvous_iv)
TUNE("SpaceCrusad"/*e"*/, space_crusade)
TUNE("StarDragon", stardragon)
TUNE("StarDragon "/*Hall of Fame"*/, stardragon_hall_of_fame)
TUNE("Terra Crest"/*a"*/, terra_cresta)
TUNE("TerraCresta", terra_cresta_)
TUNE("Tetris2", tetris2)
TUNE("The Last V8", the_last_v8)
TUNE("View to a K"/*ill"*/, view_to_a_kill)
TUNE("Where Time "/*Dropped Dead"*/, where_time_dropped_dead)
TUNE("ZUB", zub)
